engines:
  # ... CONFIG CONTENT ...
  checkstyle:
    enabled: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.naming.PackageNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.ParameterNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.AvoidStarImportCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.AbbreviationAsWordInNameCheck:
        enabled: false
  csslint:
    enabled: false
# ... CONFIG CONTENT ...
exclude_paths:
- "png/"
- "target/"
- "src/test/coverage/"
- "src/test/resources/lib/"