engines:
  # L
  # O
  # N
  # G
  #
  # L
  # I
  # V
  # E
  # 
  # T
  # H
  # E
  #
  # C
  # H
  # I
  # E
  # F
  checkstyle:
    enabled: true
    channel: "beta"
    checks:
      com.puppycrawl.tools.checkstyle.checks.naming.PackageNameCheck:
        enabled: false #Idk why this check exists
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck:
        enabled: false #I also dk why this check exists
      com.puppycrawl.tools.checkstyle.checks.naming.ParameterNameCheck:
        enabled: false #Ok this makes a little more sense
      com.puppycrawl.tools.checkstyle.checks.naming.LocalVariableNameCheck:
        enabled: false #Really...
      com.puppycrawl.tools.checkstyle.checks.naming.MemberNameCheck:
        enabled: false #Dont really understand this either
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: false #Maybe we should reenable this, jk we are definetly not
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false #wtf why
      com.puppycrawl.tools.checkstyle.checks.imports.AvoidStarImportCheck:
        enabled: false #dk what this is
      com.puppycrawl.tools.checkstyle.checks.naming.AbbreviationAsWordInNameCheck:
        enabled: false #no
  csslint:
    enabled: false
# ... CONFIG CONTENT ...
ratings:
  paths:
  - "**.java"
exclude_paths:
- "output/*"
- "target/*"
- "demo/*"
- "S3/*"
- "src/test/resources/lib/*"