engines:
  # L
  # O
  # N
  # G
  #
  # L
  # I
  # V
  # E
  # 
  # T
  # H
  # E
  #
  # C
  # H
  # I
  # E
  # F
  checkstyle:
    enabled: true
    channel: "beta"
    checks:
      com.puppycrawl.tools.checkstyle.checks.naming.PackageNameCheck:
        enabled: false #Disabled because repo name-structure causes issues
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck:
        enabled: false #Disabled because it asks for Javadocs we don't have
      com.puppycrawl.tools.checkstyle.checks.naming.ParameterNameCheck:
        enabled: false #Disabled because it doesn't allow names such as i, which are completely understandable in methods such as twoOpt
      com.puppycrawl.tools.checkstyle.checks.naming.LocalVariableNameCheck:
        enabled: false #Disabled because it doesn't allow names such as i, which are completely understandable in methods such as twoOpt
      com.puppycrawl.tools.checkstyle.checks.naming.MemberNameCheck:
        enabled: false #Disabled because it doesn't allow names such as i, which are completely understandable in methods such as twoOpt
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: true
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: true
      com.puppycrawl.tools.checkstyle.checks.imports.AvoidStarImportCheck:
        enabled: true
      com.puppycrawl.tools.checkstyle.checks.naming.AbbreviationAsWordInNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.whitespace.OperatorWrapCheck:
        enabled: false #Disabled because + should be the last thing on the line, not the first thing. This check literally makes no sense
  csslint:
    enabled: false
# ... CONFIG CONTENT ...
ratings:
  paths:
  - "**.java"
exclude_paths:
- "output/*"
- "target/*"
- "demo/*"
- "S3/*"
- "src/test/resources/lib/*"